name: BedrockUUIDChecker
version: 1.0.0
main: com.example.bedrockuuidchecker.BedrockUUIDChecker
api-version: 1.20
description: Mendeteksi dan menangani UUID bug pada player Bedrock
author: YourName

softdepend:
  - floodgate
  - Geyser-Spigot
