name: BedrockUUIDChecker
version: 1.2.0
main: com.example.bedrockuuidchecker.BedrockUUIDChecker
api-version: 1.21
description: Mendeteksi dan memblokir UUID bug pada player Bedrock di PreLogin
author: YourName

softdepend:
  - floodgate
  - Geyser-Spigot
